blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/xobotyi/css-loader-incremental-ident/discussions
    about: This is a bug tracker, not a support system. For usage questions, please use GitHub Discussions.
